name: iyox_wormhole
description: Mobile Client for the magic-wormhole protocol
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # flutter rust interop
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.77.0
  #meta: ^1.9.1
  freezed_annotation: ^2.2.0

  #file open
  file_picker: ^5.3.1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ffigen: ^8.0.2

  build_runner: ^2.4.4
  freezed: ^2.3.4

flutter:
  uses-material-design: true