name: iyox_wormhole
description: Mobile Client for the magic-wormhole protocol
publish_to: 'none'

version: 0.0.2+14

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # flutter rust interop
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.77.0
  #meta: ^1.9.1
  freezed_annotation: ^2.2.0

  #file open
  file_picker: ^5.3.1
  path_provider: ^2.0.15

  #qr
  flutter_zxing: ^1.5.2
  barcode_widget: ^2.0.4

  vibration: ^1.7.7
  dynamic_color: ^1.6.9
  statusbarz: ^1.0.12
  animations: ^2.0.11
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ffigen: ^8.0.2

  build_runner: ^2.4.4
  freezed: ^2.3.4

  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "icon/logo.png"
  android: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "icon/logo.png"