name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iyox-studios/flutter_rust
      volumes:
        - ${{ GITHUB.WORKSPACE }}:/root/wormhole
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: |
          make lint
  build_android:
    name: Build Android
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iyox-studios/flutter_rust
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Android
        run: |
          make get-dep
          make apk
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: |
            build/linux/x64/release/bundle/

  build_linux:
    name: Build Linux
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iyox-studios/flutter_rust
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Linux
        run: |
          make get-dep
          RUST_COMPILE=/root/.cargo/bin/rustc make linux
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: |
            build/app/outputs/apk/*.apk
            build/app/outputs/bundle/*.aab
